#####
# Host config for cumulus-segment-routing
#####

- hosts: switches
  become: true
  roles:
    - { role: switches, tags: ["switches"] }

- hosts: servers
  become: true
  roles:
    - { role: servers, tags: ["servers"] }
    - { role: serverExtras, tags: ["serverExtras"] }
