---

- name: Install traceroute
  apt:
    name: traceroute
    update_cache: yes

## Specific to Ubuntu 18 LTS:
#- name: Remove ifupdown1 and netplan
#  apt:
#    name: ['ifupdown','ifenslave','netplan.io']
#    state: absent

## Add the mpls_iptunnel module
- modprobe:
    name: mpls_iptunnel
    state: present

- name: Add MPLS Routes to host1
  command: ip route add 192.168.22.222/32 encap mpls 103 via inet 192.168.11.1
  when: inventory_hostname == "host1"

- name: Add MPLS Routes to host2
  command: ip route add 192.168.11.111/32 encap mpls 101 via inet 192.168.22.1
  when: inventory_hostname == "host2"

- name: Flush Handlers, best practice
  meta: flush_handlers
