---
- name: Copy host interface configuration
  template:
    src: interfaces-host.j2
    dest: /etc/network/interfaces
    backup: yes
    notify: reload networking

- name: Sleep for server to disconnect
  pause:
    seconds: 5

# - name: reboot
#   reboot:
#     pre_reboot_delay: 60

- name: Flush Handlers, best practice
  meta: flush_handlers
