---
- name: Copy host1 interfaces configuration
  template:
    src: interfaces-odd.j2
    dest: /etc/network/interfaces
    backup: yes
    notify: reload networking
  when: (ansible_hostname == "host1")

- name: Copy host2 interfaces configuration
  template:
    src: interfaces-even.j2
    dest: /etc/network/interfaces
    backup: yes
    notify: reload networking
  when: (ansible_hostname == "host2")

- name: Sleep for server to disconnect
  pause:
    seconds: 5

# - name: reboot
#   reboot:
#     pre_reboot_delay: 60

- name: Flush Handlers, best practice
  meta: flush_handlers
